---
title: "Methodology"
author: "Kristoff Dudek"
date: "2022-11-26"
output: html_document
---
*This document is a record of my thought processes and work path I have chosen for my analysis. For the stakeholder version of the report please see MM_ETF_Report*

# Introduction
The mine goal of this work is an automation of all weekly tasks associated with managing my investment portfolio.

# Assumptions and goals
* All data should be pulled from public, free sources
* The report should be in a form of summary of the situation and recommendation (in PDF format)
* I want to see one year of weekly momentum in the report.
* Additionally, I need the weekly ETF momentum calculations added every week to my Google Sheets.
* For obvious security reason I can't publish my Google credential here so the outcomes will be stored in my local SQL database.
* There is no data for SGLN ETF available on Yahoo Finance I need some substitute for it.
* In the final report should be only 3 top momentum ETFs with global bonds and phisical gold (5 in total)
* The top one is recommended but not if a failsafe rule is triggered.
* As the failsafe rule I am going to use 30 weeks Exponential Moving Average EMA(30). Asset under it can not be recommended and if all are in negative then going to cash should be advised.


## Setting Up The Environment

I am using two packages:
* Quantmod
* Tidyverse

```{r}
install.packages("quantmod")
install.packages("tidyverse")
library(quantmod)
library(tidyverse)
```